[package]
name = "lump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.3" }
dioxus-desktop = { version = "0.3" }
futures-channel = "0.3.19"
futures = "0.3.19"
regex = "1.5"